//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Students.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Students
    {
        public int studentId { get; set; }
        public string studentFirstName { get; set; }
        public string studentLastName { get; set; }
        public Nullable<System.DateTime> studentDOB { get; set; }
        public Nullable<int> age { get; set; }
        public string Address { get; set; }
    }
}
